b04bf = {
	"packag": {
		"head": {
			"busenissType": "2",
			"busseID": "B04",
			"clientmacAddress": "005056c00008",
			"hosorgName": "his_admin",
			"hosorgNum": "001",
			"intermediaryCode": "003",
			"intermediaryName": "第三方的名称",
			"receiverCode": "002",
			"receiverName": "MOS",
			"recordCount": "1",
			"sendTradeNum": "1001-2020090124-e084a32d82fc4a528d01c7d5077a6ef9",
			"senderCode": "001",
			"senderName": "HIS",
			"standardVersionCode": "version:1.0.0",
			"systemType": "1"
		},
		"additionInfo": {
			"asyncAsk": "0",
			"callback": "http://127.0.0.1:8080/xxxx/xxxx.do",
			"correlationId": "",
			"curDllAddr": "",
			"errorCode": "",
			"errorMsg": "",
			"receiverTradeNum": ""
		},
		"body": {
			"newSettlementSerialNumber": "dc42607637c44a0d8781d4bcb7b1b89x",
			"oldSettlementSerialNumber": "dc42607637c44a0d8781d4bcb7b1b89y",
			"medDataList": [
					{
						"medicalNum": "001",
						"feeItemType": "0",
						"feeType": "1",
						"prescriptionNum": "0",
						"prescriptionDateStr": "2020-09-10 15:26:09",
						"feeItemCenterCode": "AAA",
						"feeItemCode": "0",
						"feeItemName": "0",
						"unitPrice": "0.01",
						"quantity": "1",
						"dosageForm": "0",
						"specification": "0",
						"perDosage": "0",
						"frequencyOfUse": "0",
						"prescriptionDocName": "0",
						"prescriptionDocCode": "0",
						"usage": "0",
						"unit": "盒",
						"deptName": "0",
						"executeDays": "0",
						"herbalCompoundFlag": "0",
						"updateBy": "0",
						"drugDosageUnit": "0",
						"amount": "0.01",
						"selfCareAmount": "0",
						"deductibleAmount": "0",
						"overdosePersonalDeductible": "0",
						"overdoseHosDeductible": "0",
						"fundDirectPaymentAmount": "0",
						"feeItemLevel": "0",
						"fullSelfPayFlag": "0168",
						"outpatientClinicFlag": "康复科"
					}
				],
			"payData": {
				"birthday": "1970-06-08 00:00:00",
				"bunkId": "B306-14",
				"clientStatus": "10",
				"companyName": "乌拉特后旗总工会",
				"conditionDescription": "腰椎间盘突出",
				"credentialNum": "110101199003185097",
				"credentialType": "身份证",
				"currMedicalCost": "2.34",
				"endemicArea": "15",
				"gender": "2",
				"homeAddress": "内蒙古巴彦淖尔市乌拉特后旗巴音镇宝音图街东升嘉园14号2单元301室",
				"idCard": "110101199003185097",
				"inHosDiagnosisCode": "BD39",
				"inHosDiagnosisName": "腰椎间盘突出",
				"inHosDoctorCode": "01680018",
				"inHosDoctorName": "巴图",
				"inHospitalNum": "2020090124",
				"isInSocialSecurityFlg": "",
				"linkmanMobile": "13190808165",
				"linkmanName": "资福广",
				"medicalNum": "2020090124",
				"medicalType": "0",
				"name": "资福广",
				"outHosDiagnosisCode": "腰椎间盘突出",
				"outHosDiagnosisName": "腰椎间盘突出",
				"outHosDoctorCode": "01680018",
				"outHosDoctorName": "巴图",
				"outdiagnosisCode1": "",
				"outdiagnosisCode2": "",
				"outdiagnosisCode3": "",
				"outdiagnosisCode4": "",
				"outdiagnosisName1": "",
				"outdiagnosisName2": "",
				"outdiagnosisName3": "",
				"outdiagnosisName4": "",
				"race": "02",
				"remark": "",
				"socialNumber": "",
				"socialSecurityNm": "",
				"treatDateStr": "2020-09-10 15:26:09",
				"treatDeptCode": "0168",
				"treatDeptName": "康复科",
				"updateBy": "his_admin",
				#"payCode": "8000001111269032",
                "payCode":"8100001111269280"
			},
			"type": 0,
            "deductionType": 0,
			"costData": {
				"cashPay": "",
				"civilServiceGrantPay": "",
				"debitStatementNum": "",
				"detailCount": 1,
				"feeDetailList": [
					{
						"deductibleAmount": 436.29,
						"deductibleRatio": 0.0977,
						"dischargeWithMedicine": "0",
						"dosage": "",
						"feeDateStr": "2020-09-11 10:26:48",
						"feeDeptCode": "0168",
						"feeDeptName": "康复科",
						"feeEndemicAreaBedNum": "B306-14",
						"feeEndemicAreaCode": "0168",
						"feeEndemicAreaName": "康复科",
						"feeItemCode": "10002150",
						"frequency": "",
						"hosFeeItemCname": "手掌参三十七味丸",
						"hosFeeItemCode": "10002150",
						"hosFeeItemEname": "",
						"instructions": "",
						"itemCount": 60.0,
						"itemMedicareAmount": 114.0,
						"itemType": "1",
						"itenAmount": 114.0,
						"manufacturer": "鄂尔多斯市蒙医研究所制剂室",
						"mecicineCode": "",
						"medicalAdviceNum": "",
						"medicalServicesCode": "",
						"medicareFeeItemCode": "Z000001210",
						"medicineDosageForm": "",
						"medicineSpecifications": "",
						"medicineType": "1",
						"medicineWay": "",
						"perDosage": "15",
						"remark": "",
						"retailUnitPrice": 1.9,
						"salesUnit": "丸"
					}
				],
				"hospitalCode": "1001",
				"inHosRegisterId": "2020090124",
				"insurancePay":"0.01",
				"insuredAddressCode": "1345643",
				"insuredCode": "2610931151",
				"insuredCompanyCode": "",
				"insuredTypeCode": "02",
				"insuredUserType": "21",
				"medicalNum": "2020090124",
				"medicareAmount": 4463.7,
				"medicareDetailCount": 1,
				"mutualHelpPay": "",
				"offsetFlag": "0",
				"ownExpensePayAmount": "",
				"personanAccountPay": "",
				"poolFundPay": "",
				"remark": "",
				"selfPay": "",
				"settlementDateStr": "2020-09-18 00:00:00",
				"settlementType": "出院结算",
				"settlementUser": "",
				"statementSerialNum": "2020090124",
				"totalAmount": 4463.7
			}
		}
	}
}
